### ISSUE TITLE
IPFS pinning throws an error

### ISSUE THREAD

**Issue by AaronAbuUsama** [aragon/simple-storage-example-plugin#2]
the `ipfs-upload.ts` helper function throws an error
```
Error: ERROR processing /Users/main/Desktop/delme-next/deploy/02_repo/10_publish_r1b1_in_new_repo.ts:
TypeError: RequestInit: duplex option is required when sending a body.
```

MacBook Pro
16-inch, 2021
Apple M1 Pro
32GB

node: v18.15.0

**Comment by heueristik** [comment]
@pythonpete32 On which branch / commit do you experience the error?

**Comment by AaronAbuUsama** [comment]
main

**Comment by heueristik** [comment]
This is a node problem (see https://github.com/nodejs/node/issues/46221). Try using node version 16.15.1 instead (see https://github.com/aragon/simple-storage-example-plugin/blob/main/.gitpod.Dockerfile). This should fix it for now.

**Comment by tx0c** [comment]
but node v16 is been deprecating on many platforms like AWS, Vercel, ... etc;

do you guys have a solution for Node version v18 and above; thanks
